### ISSUE TITLE
Where is the release section at the code page?

### ISSUE THREAD

**Issue by Limyx826** [2TallTyler/improved_town_layouts#33]
Your repository is kind of different compare to other repo on GitHub in the sense that people usually cannot access this repo release page by UI. However it still can be access directly to the webpage by its link: https://github.com/2TallTyler/improved_town_layouts/releases

Just for comparison: 
![image](https://user-images.githubusercontent.com/38696851/115997358-62614d00-a615-11eb-82a3-59de2bd7262a.png)
![image](https://user-images.githubusercontent.com/38696851/115997448-b2401400-a615-11eb-853b-08543add1977.png)

**Comment by 2TallTyler** [comment]
I turned off the releases page because I release through the in-game content downloader (BaNaNaS), making maintaining GitHub releases an unnecessary chore. I'm not aware of a use case where people would need a manual download, but could be convinced otherwise since it's not THAT much work.

**Comment by Limyx826** [comment]
Oh I see no wonder why can't find it.
